### ISSUE TITLE
Fix links in documentation for Developing a Pants Plugin

### ISSUE THREAD

**Issue by a-shkarupin** [pantsbuild/pantsbuild.github.io#11]
Under https://v1.pantsbuild.org/howto_plugin.html links to pants repository lead to a 404 page not found result.

Examples:
https://github.com/pantsbuild/pants/blob/main/src/python/pants/backend/jvm/register.py
https://github.com/pantsbuild/pants/blob/main/src/python/pants/task/task.py

**Comment by benjyw** [comment]
Hi @a-shkarupin , this is old documentation for a deprecated version. Did you discover these broken links manually while trying to use the documentation, or via a link checker?

**Comment by a-shkarupin** [comment]
Manually, while trying to use documentation.

**Comment by benjyw** [comment]
Thanks for clarifying. What languages are you using or intending to use Pants with? If your repo is Python and you're able to use 2.x then that is generally better than using 1.x. But unrelated I will look into fixing the old docs links. Thanks for the report!

**Comment by benjyw** [comment]
Fixed. Thanks again!
